name: netease_music_api
version: 1.0.0
author: "-"
homepage: https://github.com/ziming1/NeteaseCloudMusicApi
description: netease music api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ">=2.0.0 <3.0.0"
  path: ^1.8.0
  pedantic: ^1.11.1
  encrypt: ^5.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.16.5